services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user:
    build: ./user
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres

  ticket-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - ticket-postgres-data:/var/lib/postgresql/data
      - ./ticket/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
  ticket-postgres-data: