CREATE TABLE IF NOT EXISTS EVENTS (
    EV_ID BIGSERIAL PRIMARY KEY,
    EV_NAME VARCHAR(255) NOT NULL,
    EV_HOST VARCHAR(255) NOT NULL,
    EV_DESCRIPTION TEXT,
    EV_VENUE VARCHAR(255) NOT NULL,
    EV_DATETIME TIMESTAMP NOT NULL,
    EV_TOTAL_SEATS INTEGER NOT NULL,
    EV_TICKETS_SOLD INTEGER NOT NULL,
    EV_CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS TICKET (
    TI_ID BIGSERIAL PRIMARY KEY,
    TI_EVENT_ID BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    TI_SEAT_NUMBER VARCHAR(10) NOT NULL,
    TI_SECTION VARCHAR(50) NOT NULL,
    TI_PRICE DECIMAL(10, 2) NOT NULL,
    TI_STATUS VARCHAR(20) NOT NULL DEFAULT 'available',
    TI_LOCKED_BY BIGINT,
    TI_LOCKED_UNTIL TIMESTAMP,
    TI_CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE(event_id, seat_number)
);

ALTER TABLE TICKET ADD CONSTRAINT TI_STATUS CHECK (Status IN ('available', 'locked', 'sold'));
CREATE INDEX idx_tickets_event_id ON tickets(event_id);
CREATE INDEX idx_tickets_status ON tickets(status);
CREATE INDEX idx_events_date ON events(date);